service: mapwise
image: edy-ai-playground/mapwise/mapwise

servers:
  web:
    - 34.135.208.39

registry:
  server: us-central1-docker.pkg.dev
  username: oauth2accesstoken
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    WEB_CONCURRENCY: 2

volumes:
  - "mapwise_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: edy
  keys:
    - ~/.ssh/google_compute_engine

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
