service: <%= ENV.fetch("DEPLOY_SERVICE", "mapwise") %>
image: <%= ENV.fetch("DEPLOY_IMAGE", "mapwise") %>

servers:
  web:
    - <%= ENV["DEPLOY_HOST"] %>
  job:
    hosts:
      - <%= ENV["DEPLOY_HOST"] %>
    cmd: bin/jobs

registry:
  server: <%= ENV.fetch("DEPLOY_REGISTRY", "us-central1-docker.pkg.dev") %>
  username: <%= ENV.fetch("DEPLOY_REGISTRY_USERNAME", "oauth2accesstoken") %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    WEB_CONCURRENCY: 2
    MAILER_HOST: <%= ENV["DEPLOY_HOST"] %>

volumes:
  - "<%= ENV.fetch("DEPLOY_VOLUME", "mapwise_storage") %>:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: <%= ENV.fetch("DEPLOY_SSH_USER", "root") %>
  <% if ENV["DEPLOY_SSH_KEY"] %>
  keys:
    - <%= ENV["DEPLOY_SSH_KEY"] %>
  <% end %>

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
